title:  Bruce Chidley
logo: /assets/img/Headshot_circle_191.png
description: >

 <a href="https://www.linkedin.com/in/bruce-chidley-908659249/"> <img src="https://icons8.com/icon/13930/linkedin"> </a> 

#show_downloads: true
theme: jekyll-theme-minimal
