title:  Bruce Chidley
logo: /assets/img/Headshot_circle_191.png
description: >

 <a href="https://www.linkedin.com/in/jacob-lundeen-b49b8390/"> <img src="https://img.shields.io/badge/LinkedIn-blue?logo=LinkedIn"> </a> 

#show_downloads: true
theme: jekyll-theme-minimal
