title:  Bruce Chidley
logo: /assets/img/Headshot_circle_191.png
description: >

 <a href="https://www.linkedin.com/in/bruce-chidley-908659249/"> <img src="coollogo.com/generator/?script=cookies-logo&backgroundStarburstColorAlt=%23FFFFFF"> </a> 

#show_downloads: true
theme: jekyll-theme-minimal
