title:  Bruce Chidley
logo: /assets/img/Headshot_circle_191.png
description: >

 <a href="https://www.linkedin.com/in/bruce-chidley-908659249/"> <img src="/assets/img/LinkedIn_icon_40.png"> </a> 
 <a href="https://www.linkedin.com/in/bruce-chidley-908659249/"> <img src="/assets/img/github.png" style="height: 41px; width: 40px"> </a> 
#show_downloads: true
theme: jekyll-theme-minimal
